apiVersion: apps/v1
kind: Deployment
metadata: 
  name: consignment-service-deployment
  labels:
    app: consignment-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: consignment-service
  template:
    metadata:
      labels:
        app: consignment-service
    spec:
      containers:
      - name: consignment-service
        image: shippy-consignment-service
        imagePullPolicy: Never
        ports:
          - containerPort: 50051
        env:
          - name: GRPC_ADDRESS
            value: :50051
          - name: DB_HOST
            value: consignment-service-database
          - name: DB_PORT
            value: "27017"
          - name: USER_SERVICE_ADDRESS
            value: "user-service:50051"
          - name: VESSEL_SERVICE_ADDRESS
            value: "vessel-service:50051"
