apiVersion: apps/v1
kind: Deployment
metadata: 
  name: consignment-service-deployment
  labels:
    app: consignment-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: consignment-service
  template:
    metadata:
      labels:
        app: consignment-service
    spec:
      containers:
      - name: consignment-service
        image: shippy-consignment-service
        imagePullPolicy: Never
        ports:
          - containerPort: 50051
        env:
          - name: GRPC_ADDRESS
            value: ":50051"
          - name: DB_HOST
            value: consignment-service-database
          - name: DB_PORT
            value: "27017"
          - name: RESERVATION_SERVICE_ADDRESS
            value: "reservation-service:50051"
          - name: PAYMENT_SERVICE_ADDRESS
            value: "payment-service:50051"
          - name: KAFKA_ADDRESS
            value: "kafka:9092"
          - name: OUTBOX_INTERVAL
            value: "5"
          - name: METRICS_ADDRESS
            value: ":9090"
          - name: OTEL_EXPORTER_OTLP_ENDPOINT
            value: "tempo:4317"
        readinessProbe:
          grpc:
            port: 50051
          initialDelaySeconds: 10
          periodSeconds: 5
        livenessProbe:
          grpc:
            port: 50051
          initialDelaySeconds: 30
          periodSeconds: 15
