apiVersion: v1
kind: Service
metadata:
  name: consignment-service
  labels:
    app: consignment-service
spec: 
  selector:
    app: consignment-service
  ports:
    - name: grpc
      port: 50051
      targetPort: 50051
      protocol: TCP
    - name: metrics
      port: 9090
      targetPort: 9090
  type: ClusterIP
