apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: consignment-service-database
spec:
  selector:
    matchLabels:
      app: consignment-service-database
  serviceName: consignment-service-database
  replicas: 1
  minReadySeconds: 0
  template:
    metadata:
      labels:
        app: consignment-service-database
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: consignment-service-database
        image: mongo
        ports:
        - containerPort: 27017
          name: mongodb
        volumeMounts:
        - name: consignment-db-data
          mountPath: /data/db
  volumeClaimTemplates:
  - metadata:
      name: consignment-db-data
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 1Gi
