# docker-compose.yml
services:

  # Services
  consignment:
    restart: always
    build:
      context: .
      dockerfile: consignment-service/Dockerfile
    depends_on:
      - datastore
      - vessel
    ports:
      - 50051:50051
    environment:
      MICRO_SERVER_ADDRESS: ":50051"
      DB_HOST: "mongodb://datastore:27017"

  vessel:
    restart: always
    build: ./vessel-service
    ports:
      - 50052:50051
    environment:
      MICRO_SERVER_ADDRESS: ":50051"
      DB_HOST: "mongodb://datastore:27017"

  user:
    build: ./user-service
    ports:
      - 50053:50051
    environment:
      MICRO_SERVER_ADDRESS: ":50051"
      MICRO_BROKER: nats
      MICRO_BROKER_ADDRESS: nats:4222
      DB_PASSWORD: "password"
      DB_USER: "admin"
      DB_NAME: "shippy"
      DB_HOST: "database"
    depends_on:
      - database
      - nats

  email:
    build:
      context: .
      dockerfile: email-service/Dockerfile
    environment:
      MICRO_BROKER: nats
      MICRO_BROKER_ADDRESS: nats:4222
    depends_on:
      - nats



  # Message broker
  nats:
    image: nats
    ports:
      - 4222:4222

  # Database tier
  datastore:
    image: mongo
    container_name: "datastore"
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - ./data/db:/data/db # ensures data persistence between restarting
    ports:
      - 27017
    command: mongod --logpath=/dev/null

  database:
    image: postgres:alpine
    environment:
      POSTGRES_PASSWORD: "password"
      POSTGRES_USER: "admin"
      POSTGRES_DB: "shippy"
    ports:
      - 5432:5432
    volumes:
      - ./user-service/sql/init.sql:/docker-entrypoint-initdb.d/init.sql

  # Commands
  consignment-cli:
    build:
      context: .
      dockerfile: cmd/consignment-cli/Dockerfile
    profiles:
      - cli
    
  user-cli:
    build:
      context: .
      dockerfile: cmd/user-cli/Dockerfile
    profiles:
      - cli
