apiVersion: v1
kind: Service
metadata:
  name: reservation-db
  labels:
    app: reservation-db
spec:
  selector:
    app: reservation-db
  clusterIP: None
  ports:
  - name: db
    port: 5432
    targetPort: 5432
