apiVersion: v1
kind: Service
metadata:
  name: user-service-database
  labels:
    app: user-service-database
spec:
  selector:
    app: user-service-database
  type: ClusterIP
  clusterIP: None
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
      protocol: TCP
