apiVersion: v1
kind: Secret
metadata:
  name: postgres-creds
type: Opaque
stringData:
  user: admin
  password: password
---
apiVersion: v1
kind: Secret
metadata:
  name: jwt-secret
type: Opaque
stringData:
  secret: 415290769594460e2e485922904f345d
