// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v5.29.3
// source: proto/vessel/vessel.proto

package vessel

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	VesselService_ReserveCapacity_FullMethodName = "/vessel.VesselService/ReserveCapacity"
	VesselService_ReleaseCapacity_FullMethodName = "/vessel.VesselService/ReleaseCapacity"
	VesselService_ConfirmCapacity_FullMethodName = "/vessel.VesselService/ConfirmCapacity"
	VesselService_Create_FullMethodName          = "/vessel.VesselService/Create"
)

// VesselServiceClient is the client API for VesselService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type VesselServiceClient interface {
	ReserveCapacity(ctx context.Context, in *Specification, opts ...grpc.CallOption) (*Response, error)
	ReleaseCapacity(ctx context.Context, in *CapacityRequest, opts ...grpc.CallOption) (*Empty, error)
	ConfirmCapacity(ctx context.Context, in *CapacityRequest, opts ...grpc.CallOption) (*Empty, error)
	Create(ctx context.Context, in *Vessel, opts ...grpc.CallOption) (*Response, error)
}

type vesselServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewVesselServiceClient(cc grpc.ClientConnInterface) VesselServiceClient {
	return &vesselServiceClient{cc}
}

func (c *vesselServiceClient) ReserveCapacity(ctx context.Context, in *Specification, opts ...grpc.CallOption) (*Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Response)
	err := c.cc.Invoke(ctx, VesselService_ReserveCapacity_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vesselServiceClient) ReleaseCapacity(ctx context.Context, in *CapacityRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, VesselService_ReleaseCapacity_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vesselServiceClient) ConfirmCapacity(ctx context.Context, in *CapacityRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, VesselService_ConfirmCapacity_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vesselServiceClient) Create(ctx context.Context, in *Vessel, opts ...grpc.CallOption) (*Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Response)
	err := c.cc.Invoke(ctx, VesselService_Create_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// VesselServiceServer is the server API for VesselService service.
// All implementations must embed UnimplementedVesselServiceServer
// for forward compatibility.
type VesselServiceServer interface {
	ReserveCapacity(context.Context, *Specification) (*Response, error)
	ReleaseCapacity(context.Context, *CapacityRequest) (*Empty, error)
	ConfirmCapacity(context.Context, *CapacityRequest) (*Empty, error)
	Create(context.Context, *Vessel) (*Response, error)
	mustEmbedUnimplementedVesselServiceServer()
}

// UnimplementedVesselServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedVesselServiceServer struct{}

func (UnimplementedVesselServiceServer) ReserveCapacity(context.Context, *Specification) (*Response, error) {
	return nil, status.Error(codes.Unimplemented, "method ReserveCapacity not implemented")
}
func (UnimplementedVesselServiceServer) ReleaseCapacity(context.Context, *CapacityRequest) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method ReleaseCapacity not implemented")
}
func (UnimplementedVesselServiceServer) ConfirmCapacity(context.Context, *CapacityRequest) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method ConfirmCapacity not implemented")
}
func (UnimplementedVesselServiceServer) Create(context.Context, *Vessel) (*Response, error) {
	return nil, status.Error(codes.Unimplemented, "method Create not implemented")
}
func (UnimplementedVesselServiceServer) mustEmbedUnimplementedVesselServiceServer() {}
func (UnimplementedVesselServiceServer) testEmbeddedByValue()                       {}

// UnsafeVesselServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to VesselServiceServer will
// result in compilation errors.
type UnsafeVesselServiceServer interface {
	mustEmbedUnimplementedVesselServiceServer()
}

func RegisterVesselServiceServer(s grpc.ServiceRegistrar, srv VesselServiceServer) {
	// If the following call panics, it indicates UnimplementedVesselServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&VesselService_ServiceDesc, srv)
}

func _VesselService_ReserveCapacity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Specification)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VesselServiceServer).ReserveCapacity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VesselService_ReserveCapacity_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VesselServiceServer).ReserveCapacity(ctx, req.(*Specification))
	}
	return interceptor(ctx, in, info, handler)
}

func _VesselService_ReleaseCapacity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CapacityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VesselServiceServer).ReleaseCapacity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VesselService_ReleaseCapacity_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VesselServiceServer).ReleaseCapacity(ctx, req.(*CapacityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VesselService_ConfirmCapacity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CapacityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VesselServiceServer).ConfirmCapacity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VesselService_ConfirmCapacity_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VesselServiceServer).ConfirmCapacity(ctx, req.(*CapacityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VesselService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Vessel)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VesselServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VesselService_Create_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VesselServiceServer).Create(ctx, req.(*Vessel))
	}
	return interceptor(ctx, in, info, handler)
}

// VesselService_ServiceDesc is the grpc.ServiceDesc for VesselService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var VesselService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "vessel.VesselService",
	HandlerType: (*VesselServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ReserveCapacity",
			Handler:    _VesselService_ReserveCapacity_Handler,
		},
		{
			MethodName: "ReleaseCapacity",
			Handler:    _VesselService_ReleaseCapacity_Handler,
		},
		{
			MethodName: "ConfirmCapacity",
			Handler:    _VesselService_ConfirmCapacity_Handler,
		},
		{
			MethodName: "Create",
			Handler:    _VesselService_Create_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/vessel/vessel.proto",
}
