// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: proto/reservation/reservation.proto

package reservation

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ReserveCapacityRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	ConsignmentId      string                 `protobuf:"bytes,1,opt,name=consignment_id,json=consignmentId,proto3" json:"consignment_id,omitempty"`
	Weight             int32                  `protobuf:"varint,2,opt,name=weight,proto3" json:"weight,omitempty"`
	NumberOfContainers int32                  `protobuf:"varint,3,opt,name=number_of_containers,json=numberOfContainers,proto3" json:"number_of_containers,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ReserveCapacityRequest) Reset() {
	*x = ReserveCapacityRequest{}
	mi := &file_proto_reservation_reservation_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReserveCapacityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReserveCapacityRequest) ProtoMessage() {}

func (x *ReserveCapacityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_reservation_reservation_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReserveCapacityRequest.ProtoReflect.Descriptor instead.
func (*ReserveCapacityRequest) Descriptor() ([]byte, []int) {
	return file_proto_reservation_reservation_proto_rawDescGZIP(), []int{0}
}

func (x *ReserveCapacityRequest) GetConsignmentId() string {
	if x != nil {
		return x.ConsignmentId
	}
	return ""
}

func (x *ReserveCapacityRequest) GetWeight() int32 {
	if x != nil {
		return x.Weight
	}
	return 0
}

func (x *ReserveCapacityRequest) GetNumberOfContainers() int32 {
	if x != nil {
		return x.NumberOfContainers
	}
	return 0
}

type ReservationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Reserved      bool                   `protobuf:"varint,2,opt,name=reserved,proto3" json:"reserved,omitempty"`
	VesselId      string                 `protobuf:"bytes,3,opt,name=vessel_id,json=vesselId,proto3" json:"vessel_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReservationResponse) Reset() {
	*x = ReservationResponse{}
	mi := &file_proto_reservation_reservation_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReservationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReservationResponse) ProtoMessage() {}

func (x *ReservationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_reservation_reservation_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReservationResponse.ProtoReflect.Descriptor instead.
func (*ReservationResponse) Descriptor() ([]byte, []int) {
	return file_proto_reservation_reservation_proto_rawDescGZIP(), []int{1}
}

func (x *ReservationResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ReservationResponse) GetReserved() bool {
	if x != nil {
		return x.Reserved
	}
	return false
}

func (x *ReservationResponse) GetVesselId() string {
	if x != nil {
		return x.VesselId
	}
	return ""
}

type CapacityActionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CapacityActionRequest) Reset() {
	*x = CapacityActionRequest{}
	mi := &file_proto_reservation_reservation_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CapacityActionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CapacityActionRequest) ProtoMessage() {}

func (x *CapacityActionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_reservation_reservation_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CapacityActionRequest.ProtoReflect.Descriptor instead.
func (*CapacityActionRequest) Descriptor() ([]byte, []int) {
	return file_proto_reservation_reservation_proto_rawDescGZIP(), []int{2}
}

func (x *CapacityActionRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_proto_reservation_reservation_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_proto_reservation_reservation_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_proto_reservation_reservation_proto_rawDescGZIP(), []int{3}
}

var File_proto_reservation_reservation_proto protoreflect.FileDescriptor

const file_proto_reservation_reservation_proto_rawDesc = "" +
	"\n" +
	"#proto/reservation/reservation.proto\x12\vreservation\"\x89\x01\n" +
	"\x16ReserveCapacityRequest\x12%\n" +
	"\x0econsignment_id\x18\x01 \x01(\tR\rconsignmentId\x12\x16\n" +
	"\x06weight\x18\x02 \x01(\x05R\x06weight\x120\n" +
	"\x14number_of_containers\x18\x03 \x01(\x05R\x12numberOfContainers\"^\n" +
	"\x13ReservationResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1a\n" +
	"\breserved\x18\x02 \x01(\bR\breserved\x12\x1b\n" +
	"\tvessel_id\x18\x03 \x01(\tR\bvesselId\"'\n" +
	"\x15CapacityActionRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\a\n" +
	"\x05Empty2\xd2\x02\n" +
	"\x12ReservationService\x12X\n" +
	"\x0fReserveCapacity\x12#.reservation.ReserveCapacityRequest\x1a .reservation.ReservationResponse\x12I\n" +
	"\x0fReleaseCapacity\x12\".reservation.CapacityActionRequest\x1a\x12.reservation.Empty\x12I\n" +
	"\x0fConfirmCapacity\x12\".reservation.CapacityActionRequest\x1a\x12.reservation.Empty\x12L\n" +
	"\x12RefreshReservation\x12\".reservation.CapacityActionRequest\x1a\x12.reservation.EmptyB5Z3github.com/murraystewart96/shippy/proto/reservationb\x06proto3"

var (
	file_proto_reservation_reservation_proto_rawDescOnce sync.Once
	file_proto_reservation_reservation_proto_rawDescData []byte
)

func file_proto_reservation_reservation_proto_rawDescGZIP() []byte {
	file_proto_reservation_reservation_proto_rawDescOnce.Do(func() {
		file_proto_reservation_reservation_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_reservation_reservation_proto_rawDesc), len(file_proto_reservation_reservation_proto_rawDesc)))
	})
	return file_proto_reservation_reservation_proto_rawDescData
}

var file_proto_reservation_reservation_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_reservation_reservation_proto_goTypes = []any{
	(*ReserveCapacityRequest)(nil), // 0: reservation.ReserveCapacityRequest
	(*ReservationResponse)(nil),    // 1: reservation.ReservationResponse
	(*CapacityActionRequest)(nil),  // 2: reservation.CapacityActionRequest
	(*Empty)(nil),                  // 3: reservation.Empty
}
var file_proto_reservation_reservation_proto_depIdxs = []int32{
	0, // 0: reservation.ReservationService.ReserveCapacity:input_type -> reservation.ReserveCapacityRequest
	2, // 1: reservation.ReservationService.ReleaseCapacity:input_type -> reservation.CapacityActionRequest
	2, // 2: reservation.ReservationService.ConfirmCapacity:input_type -> reservation.CapacityActionRequest
	2, // 3: reservation.ReservationService.RefreshReservation:input_type -> reservation.CapacityActionRequest
	1, // 4: reservation.ReservationService.ReserveCapacity:output_type -> reservation.ReservationResponse
	3, // 5: reservation.ReservationService.ReleaseCapacity:output_type -> reservation.Empty
	3, // 6: reservation.ReservationService.ConfirmCapacity:output_type -> reservation.Empty
	3, // 7: reservation.ReservationService.RefreshReservation:output_type -> reservation.Empty
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_reservation_reservation_proto_init() }
func file_proto_reservation_reservation_proto_init() {
	if File_proto_reservation_reservation_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_reservation_reservation_proto_rawDesc), len(file_proto_reservation_reservation_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_reservation_reservation_proto_goTypes,
		DependencyIndexes: file_proto_reservation_reservation_proto_depIdxs,
		MessageInfos:      file_proto_reservation_reservation_proto_msgTypes,
	}.Build()
	File_proto_reservation_reservation_proto = out.File
	file_proto_reservation_reservation_proto_goTypes = nil
	file_proto_reservation_reservation_proto_depIdxs = nil
}
