apiVersion: apps/v1
kind: Deployment
metadata: 
  name: consignment-service-deployment
  labels:
    app: consignment-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: consignment-service
  template:
    metadata:
      labels:
        app: consignment-service
    spec:
      containers:
      - name: consignment-service
        image: shippy-consignment-service
        imagePullPolicy: Never
        ports:
          - containerPort: 50051
        env:
          - name: MICRO_SERVER_ADDRESS
            value: :50051
          - name: DB_HOST
            value: consignment-service-database
