apiVersion: apps/v1
kind: Deployment
metadata: 
  name: vessel-service-deployment
  labels:
    app: vessel-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vessel-service
  template:
    metadata:
      labels:
        app: vessel-service
    spec:
      containers:
      - name: vessel-service
        image: shippy-vessel-service
        imagePullPolicy: Never
        ports:
          - containerPort: 50051
        env:
          - name: GRPC_ADDRESS
            value: :50051
          - name: DB_HOST
            value: vessel-service-database
          - name: DB_PORT
            value: "27017"
          - name: OTEL_EXPORTER_OTLP_ENDPOINT
            value: "tempo:4317"
