apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: vessel-service-database
spec:
  selector:
    matchLabels:
      app: vessel-service-database
  serviceName: vessel-service-database
  replicas: 1
  minReadySeconds: 0
  template:
    metadata:
      labels:
        app: vessel-service-database
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: vessel-service-database
        image: mongo
        command: ["mongod", "--replSet", "rs0", "--bind_ip_all", "--logpath=/dev/null"]
        ports:
        - containerPort: 27017
          name: mongodb
        volumeMounts:
        - name: vessel-db-data
          mountPath: /data/db
        readinessProbe:
          exec:
            command:
            - mongosh
            - --eval
            - "try { rs.status().ok } catch(e) { rs.initiate({_id:'rs0',members:[{_id:0,host:'vessel-service-database-0.vessel-service-database:27017'}]}).ok }"
            - --quiet
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 10
          failureThreshold: 6
  volumeClaimTemplates:
  - metadata:
      name: vessel-db-data
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 1Gi
