global:
  scrape_interval: 15s

scrape_configs:
  - job_name: consignment
    static_configs:
      - targets: ["consignment:9090"]

  - job_name: reservation
    static_configs:
      - targets: ["reservation:9090"]
