// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: proto/events/events.proto

package events

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CapacityAction int32

const (
	CapacityAction_CAPACITY_ACTION_UNSPECIFIED CapacityAction = 0
	CapacityAction_CAPACITY_ACTION_RELEASE     CapacityAction = 1
	CapacityAction_CAPACITY_ACTION_CONFIRM     CapacityAction = 2
)

// Enum value maps for CapacityAction.
var (
	CapacityAction_name = map[int32]string{
		0: "CAPACITY_ACTION_UNSPECIFIED",
		1: "CAPACITY_ACTION_RELEASE",
		2: "CAPACITY_ACTION_CONFIRM",
	}
	CapacityAction_value = map[string]int32{
		"CAPACITY_ACTION_UNSPECIFIED": 0,
		"CAPACITY_ACTION_RELEASE":     1,
		"CAPACITY_ACTION_CONFIRM":     2,
	}
)

func (x CapacityAction) Enum() *CapacityAction {
	p := new(CapacityAction)
	*p = x
	return p
}

func (x CapacityAction) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CapacityAction) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_events_events_proto_enumTypes[0].Descriptor()
}

func (CapacityAction) Type() protoreflect.EnumType {
	return &file_proto_events_events_proto_enumTypes[0]
}

func (x CapacityAction) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CapacityAction.Descriptor instead.
func (CapacityAction) EnumDescriptor() ([]byte, []int) {
	return file_proto_events_events_proto_rawDescGZIP(), []int{0}
}

type ReservationInfo struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Id                 string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	VesselId           string                 `protobuf:"bytes,2,opt,name=vessel_id,json=vesselId,proto3" json:"vessel_id,omitempty"`
	ConsignmentId      string                 `protobuf:"bytes,3,opt,name=consignment_id,json=consignmentId,proto3" json:"consignment_id,omitempty"`
	NumberOfContainers int32                  `protobuf:"varint,4,opt,name=number_of_containers,json=numberOfContainers,proto3" json:"number_of_containers,omitempty"`
	Weight             int32                  `protobuf:"varint,5,opt,name=weight,proto3" json:"weight,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ReservationInfo) Reset() {
	*x = ReservationInfo{}
	mi := &file_proto_events_events_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReservationInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReservationInfo) ProtoMessage() {}

func (x *ReservationInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_events_events_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReservationInfo.ProtoReflect.Descriptor instead.
func (*ReservationInfo) Descriptor() ([]byte, []int) {
	return file_proto_events_events_proto_rawDescGZIP(), []int{0}
}

func (x *ReservationInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ReservationInfo) GetVesselId() string {
	if x != nil {
		return x.VesselId
	}
	return ""
}

func (x *ReservationInfo) GetConsignmentId() string {
	if x != nil {
		return x.ConsignmentId
	}
	return ""
}

func (x *ReservationInfo) GetNumberOfContainers() int32 {
	if x != nil {
		return x.NumberOfContainers
	}
	return 0
}

func (x *ReservationInfo) GetWeight() int32 {
	if x != nil {
		return x.Weight
	}
	return 0
}

type PaymentAuthorisedEvent struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ConsignmentId   string                 `protobuf:"bytes,1,opt,name=consignment_id,json=consignmentId,proto3" json:"consignment_id,omitempty"`
	ReservationId   string                 `protobuf:"bytes,2,opt,name=reservation_id,json=reservationId,proto3" json:"reservation_id,omitempty"`
	VesselId        string                 `protobuf:"bytes,3,opt,name=vessel_id,json=vesselId,proto3" json:"vessel_id,omitempty"`
	PaymentAuthId   string                 `protobuf:"bytes,4,opt,name=payment_auth_id,json=paymentAuthId,proto3" json:"payment_auth_id,omitempty"`
	IdempotencyKey  string                 `protobuf:"bytes,5,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	Weight          int32                  `protobuf:"varint,6,opt,name=weight,proto3" json:"weight,omitempty"`
	Containers      int32                  `protobuf:"varint,7,opt,name=containers,proto3" json:"containers,omitempty"`
	RetryCount      int32                  `protobuf:"varint,8,opt,name=retry_count,json=retryCount,proto3" json:"retry_count,omitempty"`
	CacheCleared    bool                   `protobuf:"varint,9,opt,name=cache_cleared,json=cacheCleared,proto3" json:"cache_cleared,omitempty"`
	PaymentCaptured bool                   `protobuf:"varint,10,opt,name=payment_captured,json=paymentCaptured,proto3" json:"payment_captured,omitempty"`
	PaymentId       string                 `protobuf:"bytes,11,opt,name=payment_id,json=paymentId,proto3" json:"payment_id,omitempty"`
	SagaStartedAt   *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=saga_started_at,json=sagaStartedAt,proto3" json:"saga_started_at,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *PaymentAuthorisedEvent) Reset() {
	*x = PaymentAuthorisedEvent{}
	mi := &file_proto_events_events_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaymentAuthorisedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaymentAuthorisedEvent) ProtoMessage() {}

func (x *PaymentAuthorisedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_events_events_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaymentAuthorisedEvent.ProtoReflect.Descriptor instead.
func (*PaymentAuthorisedEvent) Descriptor() ([]byte, []int) {
	return file_proto_events_events_proto_rawDescGZIP(), []int{1}
}

func (x *PaymentAuthorisedEvent) GetConsignmentId() string {
	if x != nil {
		return x.ConsignmentId
	}
	return ""
}

func (x *PaymentAuthorisedEvent) GetReservationId() string {
	if x != nil {
		return x.ReservationId
	}
	return ""
}

func (x *PaymentAuthorisedEvent) GetVesselId() string {
	if x != nil {
		return x.VesselId
	}
	return ""
}

func (x *PaymentAuthorisedEvent) GetPaymentAuthId() string {
	if x != nil {
		return x.PaymentAuthId
	}
	return ""
}

func (x *PaymentAuthorisedEvent) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

func (x *PaymentAuthorisedEvent) GetWeight() int32 {
	if x != nil {
		return x.Weight
	}
	return 0
}

func (x *PaymentAuthorisedEvent) GetContainers() int32 {
	if x != nil {
		return x.Containers
	}
	return 0
}

func (x *PaymentAuthorisedEvent) GetRetryCount() int32 {
	if x != nil {
		return x.RetryCount
	}
	return 0
}

func (x *PaymentAuthorisedEvent) GetCacheCleared() bool {
	if x != nil {
		return x.CacheCleared
	}
	return false
}

func (x *PaymentAuthorisedEvent) GetPaymentCaptured() bool {
	if x != nil {
		return x.PaymentCaptured
	}
	return false
}

func (x *PaymentAuthorisedEvent) GetPaymentId() string {
	if x != nil {
		return x.PaymentId
	}
	return ""
}

func (x *PaymentAuthorisedEvent) GetSagaStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.SagaStartedAt
	}
	return nil
}

type PaymentCapturedEvent struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ReservationInfo *ReservationInfo       `protobuf:"bytes,1,opt,name=reservation_info,json=reservationInfo,proto3" json:"reservation_info,omitempty"`
	ConsignmentId   string                 `protobuf:"bytes,2,opt,name=consignment_id,json=consignmentId,proto3" json:"consignment_id,omitempty"`
	PaymentId       string                 `protobuf:"bytes,3,opt,name=payment_id,json=paymentId,proto3" json:"payment_id,omitempty"`
	SagaStartedAt   *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=saga_started_at,json=sagaStartedAt,proto3" json:"saga_started_at,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *PaymentCapturedEvent) Reset() {
	*x = PaymentCapturedEvent{}
	mi := &file_proto_events_events_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaymentCapturedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaymentCapturedEvent) ProtoMessage() {}

func (x *PaymentCapturedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_events_events_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaymentCapturedEvent.ProtoReflect.Descriptor instead.
func (*PaymentCapturedEvent) Descriptor() ([]byte, []int) {
	return file_proto_events_events_proto_rawDescGZIP(), []int{2}
}

func (x *PaymentCapturedEvent) GetReservationInfo() *ReservationInfo {
	if x != nil {
		return x.ReservationInfo
	}
	return nil
}

func (x *PaymentCapturedEvent) GetConsignmentId() string {
	if x != nil {
		return x.ConsignmentId
	}
	return ""
}

func (x *PaymentCapturedEvent) GetPaymentId() string {
	if x != nil {
		return x.PaymentId
	}
	return ""
}

func (x *PaymentCapturedEvent) GetSagaStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.SagaStartedAt
	}
	return nil
}

type ReservationConfirmedEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReservationId string                 `protobuf:"bytes,1,opt,name=reservation_id,json=reservationId,proto3" json:"reservation_id,omitempty"`
	ConsignmentId string                 `protobuf:"bytes,2,opt,name=consignment_id,json=consignmentId,proto3" json:"consignment_id,omitempty"`
	SagaStartedAt *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=saga_started_at,json=sagaStartedAt,proto3" json:"saga_started_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReservationConfirmedEvent) Reset() {
	*x = ReservationConfirmedEvent{}
	mi := &file_proto_events_events_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReservationConfirmedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReservationConfirmedEvent) ProtoMessage() {}

func (x *ReservationConfirmedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_events_events_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReservationConfirmedEvent.ProtoReflect.Descriptor instead.
func (*ReservationConfirmedEvent) Descriptor() ([]byte, []int) {
	return file_proto_events_events_proto_rawDescGZIP(), []int{3}
}

func (x *ReservationConfirmedEvent) GetReservationId() string {
	if x != nil {
		return x.ReservationId
	}
	return ""
}

func (x *ReservationConfirmedEvent) GetConsignmentId() string {
	if x != nil {
		return x.ConsignmentId
	}
	return ""
}

func (x *ReservationConfirmedEvent) GetSagaStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.SagaStartedAt
	}
	return nil
}

type ReservationExpiredEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReservationId string                 `protobuf:"bytes,1,opt,name=reservation_id,json=reservationId,proto3" json:"reservation_id,omitempty"`
	VesselId      string                 `protobuf:"bytes,2,opt,name=vessel_id,json=vesselId,proto3" json:"vessel_id,omitempty"`
	ConsignmentId string                 `protobuf:"bytes,3,opt,name=consignment_id,json=consignmentId,proto3" json:"consignment_id,omitempty"`
	Weight        int32                  `protobuf:"varint,4,opt,name=weight,proto3" json:"weight,omitempty"`
	Containers    int32                  `protobuf:"varint,5,opt,name=containers,proto3" json:"containers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReservationExpiredEvent) Reset() {
	*x = ReservationExpiredEvent{}
	mi := &file_proto_events_events_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReservationExpiredEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReservationExpiredEvent) ProtoMessage() {}

func (x *ReservationExpiredEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_events_events_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReservationExpiredEvent.ProtoReflect.Descriptor instead.
func (*ReservationExpiredEvent) Descriptor() ([]byte, []int) {
	return file_proto_events_events_proto_rawDescGZIP(), []int{4}
}

func (x *ReservationExpiredEvent) GetReservationId() string {
	if x != nil {
		return x.ReservationId
	}
	return ""
}

func (x *ReservationExpiredEvent) GetVesselId() string {
	if x != nil {
		return x.VesselId
	}
	return ""
}

func (x *ReservationExpiredEvent) GetConsignmentId() string {
	if x != nil {
		return x.ConsignmentId
	}
	return ""
}

func (x *ReservationExpiredEvent) GetWeight() int32 {
	if x != nil {
		return x.Weight
	}
	return 0
}

func (x *ReservationExpiredEvent) GetContainers() int32 {
	if x != nil {
		return x.Containers
	}
	return 0
}

type ConsignmentConfirmationFailedEvent struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ConsignmentId   string                 `protobuf:"bytes,1,opt,name=consignment_id,json=consignmentId,proto3" json:"consignment_id,omitempty"`
	ReservationId   string                 `protobuf:"bytes,2,opt,name=reservation_id,json=reservationId,proto3" json:"reservation_id,omitempty"`
	VesselId        string                 `protobuf:"bytes,3,opt,name=vessel_id,json=vesselId,proto3" json:"vessel_id,omitempty"`
	PaymentId       string                 `protobuf:"bytes,4,opt,name=payment_id,json=paymentId,proto3" json:"payment_id,omitempty"`
	Weight          int32                  `protobuf:"varint,5,opt,name=weight,proto3" json:"weight,omitempty"`
	Containers      int32                  `protobuf:"varint,6,opt,name=containers,proto3" json:"containers,omitempty"`
	CacheCleared    bool                   `protobuf:"varint,7,opt,name=cache_cleared,json=cacheCleared,proto3" json:"cache_cleared,omitempty"`
	PaymentCaptured bool                   `protobuf:"varint,8,opt,name=payment_captured,json=paymentCaptured,proto3" json:"payment_captured,omitempty"`
	SagaStartedAt   *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=saga_started_at,json=sagaStartedAt,proto3" json:"saga_started_at,omitempty"`
	// Only set when payment was never captured (capture retry exhaustion path).
	PaymentAuthId string `protobuf:"bytes,10,opt,name=payment_auth_id,json=paymentAuthId,proto3" json:"payment_auth_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConsignmentConfirmationFailedEvent) Reset() {
	*x = ConsignmentConfirmationFailedEvent{}
	mi := &file_proto_events_events_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConsignmentConfirmationFailedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsignmentConfirmationFailedEvent) ProtoMessage() {}

func (x *ConsignmentConfirmationFailedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_events_events_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsignmentConfirmationFailedEvent.ProtoReflect.Descriptor instead.
func (*ConsignmentConfirmationFailedEvent) Descriptor() ([]byte, []int) {
	return file_proto_events_events_proto_rawDescGZIP(), []int{5}
}

func (x *ConsignmentConfirmationFailedEvent) GetConsignmentId() string {
	if x != nil {
		return x.ConsignmentId
	}
	return ""
}

func (x *ConsignmentConfirmationFailedEvent) GetReservationId() string {
	if x != nil {
		return x.ReservationId
	}
	return ""
}

func (x *ConsignmentConfirmationFailedEvent) GetVesselId() string {
	if x != nil {
		return x.VesselId
	}
	return ""
}

func (x *ConsignmentConfirmationFailedEvent) GetPaymentId() string {
	if x != nil {
		return x.PaymentId
	}
	return ""
}

func (x *ConsignmentConfirmationFailedEvent) GetWeight() int32 {
	if x != nil {
		return x.Weight
	}
	return 0
}

func (x *ConsignmentConfirmationFailedEvent) GetContainers() int32 {
	if x != nil {
		return x.Containers
	}
	return 0
}

func (x *ConsignmentConfirmationFailedEvent) GetCacheCleared() bool {
	if x != nil {
		return x.CacheCleared
	}
	return false
}

func (x *ConsignmentConfirmationFailedEvent) GetPaymentCaptured() bool {
	if x != nil {
		return x.PaymentCaptured
	}
	return false
}

func (x *ConsignmentConfirmationFailedEvent) GetSagaStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.SagaStartedAt
	}
	return nil
}

func (x *ConsignmentConfirmationFailedEvent) GetPaymentAuthId() string {
	if x != nil {
		return x.PaymentAuthId
	}
	return ""
}

type CapacityEvent struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Action          CapacityAction         `protobuf:"varint,1,opt,name=action,proto3,enum=events.CapacityAction" json:"action,omitempty"`
	ReservationInfo *ReservationInfo       `protobuf:"bytes,2,opt,name=reservation_info,json=reservationInfo,proto3" json:"reservation_info,omitempty"`
	CacheCleared    bool                   `protobuf:"varint,3,opt,name=cache_cleared,json=cacheCleared,proto3" json:"cache_cleared,omitempty"`
	RetryCount      int32                  `protobuf:"varint,4,opt,name=retry_count,json=retryCount,proto3" json:"retry_count,omitempty"`
	ConsignmentId   string                 `protobuf:"bytes,5,opt,name=consignment_id,json=consignmentId,proto3" json:"consignment_id,omitempty"`
	PaymentId       string                 `protobuf:"bytes,6,opt,name=payment_id,json=paymentId,proto3" json:"payment_id,omitempty"`
	SagaStartedAt   *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=saga_started_at,json=sagaStartedAt,proto3" json:"saga_started_at,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CapacityEvent) Reset() {
	*x = CapacityEvent{}
	mi := &file_proto_events_events_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CapacityEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CapacityEvent) ProtoMessage() {}

func (x *CapacityEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_events_events_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CapacityEvent.ProtoReflect.Descriptor instead.
func (*CapacityEvent) Descriptor() ([]byte, []int) {
	return file_proto_events_events_proto_rawDescGZIP(), []int{6}
}

func (x *CapacityEvent) GetAction() CapacityAction {
	if x != nil {
		return x.Action
	}
	return CapacityAction_CAPACITY_ACTION_UNSPECIFIED
}

func (x *CapacityEvent) GetReservationInfo() *ReservationInfo {
	if x != nil {
		return x.ReservationInfo
	}
	return nil
}

func (x *CapacityEvent) GetCacheCleared() bool {
	if x != nil {
		return x.CacheCleared
	}
	return false
}

func (x *CapacityEvent) GetRetryCount() int32 {
	if x != nil {
		return x.RetryCount
	}
	return 0
}

func (x *CapacityEvent) GetConsignmentId() string {
	if x != nil {
		return x.ConsignmentId
	}
	return ""
}

func (x *CapacityEvent) GetPaymentId() string {
	if x != nil {
		return x.PaymentId
	}
	return ""
}

func (x *CapacityEvent) GetSagaStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.SagaStartedAt
	}
	return nil
}

var File_proto_events_events_proto protoreflect.FileDescriptor

const file_proto_events_events_proto_rawDesc = "" +
	"\n" +
	"\x19proto/events/events.proto\x12\x06events\x1a\x1fgoogle/protobuf/timestamp.proto\"\xaf\x01\n" +
	"\x0fReservationInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\tvessel_id\x18\x02 \x01(\tR\bvesselId\x12%\n" +
	"\x0econsignment_id\x18\x03 \x01(\tR\rconsignmentId\x120\n" +
	"\x14number_of_containers\x18\x04 \x01(\x05R\x12numberOfContainers\x12\x16\n" +
	"\x06weight\x18\x05 \x01(\x05R\x06weight\"\xe0\x03\n" +
	"\x16PaymentAuthorisedEvent\x12%\n" +
	"\x0econsignment_id\x18\x01 \x01(\tR\rconsignmentId\x12%\n" +
	"\x0ereservation_id\x18\x02 \x01(\tR\rreservationId\x12\x1b\n" +
	"\tvessel_id\x18\x03 \x01(\tR\bvesselId\x12&\n" +
	"\x0fpayment_auth_id\x18\x04 \x01(\tR\rpaymentAuthId\x12'\n" +
	"\x0fidempotency_key\x18\x05 \x01(\tR\x0eidempotencyKey\x12\x16\n" +
	"\x06weight\x18\x06 \x01(\x05R\x06weight\x12\x1e\n" +
	"\n" +
	"containers\x18\a \x01(\x05R\n" +
	"containers\x12\x1f\n" +
	"\vretry_count\x18\b \x01(\x05R\n" +
	"retryCount\x12#\n" +
	"\rcache_cleared\x18\t \x01(\bR\fcacheCleared\x12)\n" +
	"\x10payment_captured\x18\n" +
	" \x01(\bR\x0fpaymentCaptured\x12\x1d\n" +
	"\n" +
	"payment_id\x18\v \x01(\tR\tpaymentId\x12B\n" +
	"\x0fsaga_started_at\x18\f \x01(\v2\x1a.google.protobuf.TimestampR\rsagaStartedAt\"\xe4\x01\n" +
	"\x14PaymentCapturedEvent\x12B\n" +
	"\x10reservation_info\x18\x01 \x01(\v2\x17.events.ReservationInfoR\x0freservationInfo\x12%\n" +
	"\x0econsignment_id\x18\x02 \x01(\tR\rconsignmentId\x12\x1d\n" +
	"\n" +
	"payment_id\x18\x03 \x01(\tR\tpaymentId\x12B\n" +
	"\x0fsaga_started_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\rsagaStartedAt\"\xad\x01\n" +
	"\x19ReservationConfirmedEvent\x12%\n" +
	"\x0ereservation_id\x18\x01 \x01(\tR\rreservationId\x12%\n" +
	"\x0econsignment_id\x18\x02 \x01(\tR\rconsignmentId\x12B\n" +
	"\x0fsaga_started_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\rsagaStartedAt\"\xbc\x01\n" +
	"\x17ReservationExpiredEvent\x12%\n" +
	"\x0ereservation_id\x18\x01 \x01(\tR\rreservationId\x12\x1b\n" +
	"\tvessel_id\x18\x02 \x01(\tR\bvesselId\x12%\n" +
	"\x0econsignment_id\x18\x03 \x01(\tR\rconsignmentId\x12\x16\n" +
	"\x06weight\x18\x04 \x01(\x05R\x06weight\x12\x1e\n" +
	"\n" +
	"containers\x18\x05 \x01(\x05R\n" +
	"containers\"\xa2\x03\n" +
	"\"ConsignmentConfirmationFailedEvent\x12%\n" +
	"\x0econsignment_id\x18\x01 \x01(\tR\rconsignmentId\x12%\n" +
	"\x0ereservation_id\x18\x02 \x01(\tR\rreservationId\x12\x1b\n" +
	"\tvessel_id\x18\x03 \x01(\tR\bvesselId\x12\x1d\n" +
	"\n" +
	"payment_id\x18\x04 \x01(\tR\tpaymentId\x12\x16\n" +
	"\x06weight\x18\x05 \x01(\x05R\x06weight\x12\x1e\n" +
	"\n" +
	"containers\x18\x06 \x01(\x05R\n" +
	"containers\x12#\n" +
	"\rcache_cleared\x18\a \x01(\bR\fcacheCleared\x12)\n" +
	"\x10payment_captured\x18\b \x01(\bR\x0fpaymentCaptured\x12B\n" +
	"\x0fsaga_started_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\rsagaStartedAt\x12&\n" +
	"\x0fpayment_auth_id\x18\n" +
	" \x01(\tR\rpaymentAuthId\"\xd3\x02\n" +
	"\rCapacityEvent\x12.\n" +
	"\x06action\x18\x01 \x01(\x0e2\x16.events.CapacityActionR\x06action\x12B\n" +
	"\x10reservation_info\x18\x02 \x01(\v2\x17.events.ReservationInfoR\x0freservationInfo\x12#\n" +
	"\rcache_cleared\x18\x03 \x01(\bR\fcacheCleared\x12\x1f\n" +
	"\vretry_count\x18\x04 \x01(\x05R\n" +
	"retryCount\x12%\n" +
	"\x0econsignment_id\x18\x05 \x01(\tR\rconsignmentId\x12\x1d\n" +
	"\n" +
	"payment_id\x18\x06 \x01(\tR\tpaymentId\x12B\n" +
	"\x0fsaga_started_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\rsagaStartedAt*k\n" +
	"\x0eCapacityAction\x12\x1f\n" +
	"\x1bCAPACITY_ACTION_UNSPECIFIED\x10\x00\x12\x1b\n" +
	"\x17CAPACITY_ACTION_RELEASE\x10\x01\x12\x1b\n" +
	"\x17CAPACITY_ACTION_CONFIRM\x10\x02B0Z.github.com/murraystewart96/shippy/proto/eventsb\x06proto3"

var (
	file_proto_events_events_proto_rawDescOnce sync.Once
	file_proto_events_events_proto_rawDescData []byte
)

func file_proto_events_events_proto_rawDescGZIP() []byte {
	file_proto_events_events_proto_rawDescOnce.Do(func() {
		file_proto_events_events_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_events_events_proto_rawDesc), len(file_proto_events_events_proto_rawDesc)))
	})
	return file_proto_events_events_proto_rawDescData
}

var file_proto_events_events_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_events_events_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_proto_events_events_proto_goTypes = []any{
	(CapacityAction)(0),                        // 0: events.CapacityAction
	(*ReservationInfo)(nil),                    // 1: events.ReservationInfo
	(*PaymentAuthorisedEvent)(nil),             // 2: events.PaymentAuthorisedEvent
	(*PaymentCapturedEvent)(nil),               // 3: events.PaymentCapturedEvent
	(*ReservationConfirmedEvent)(nil),          // 4: events.ReservationConfirmedEvent
	(*ReservationExpiredEvent)(nil),            // 5: events.ReservationExpiredEvent
	(*ConsignmentConfirmationFailedEvent)(nil), // 6: events.ConsignmentConfirmationFailedEvent
	(*CapacityEvent)(nil),                      // 7: events.CapacityEvent
	(*timestamppb.Timestamp)(nil),              // 8: google.protobuf.Timestamp
}
var file_proto_events_events_proto_depIdxs = []int32{
	8, // 0: events.PaymentAuthorisedEvent.saga_started_at:type_name -> google.protobuf.Timestamp
	1, // 1: events.PaymentCapturedEvent.reservation_info:type_name -> events.ReservationInfo
	8, // 2: events.PaymentCapturedEvent.saga_started_at:type_name -> google.protobuf.Timestamp
	8, // 3: events.ReservationConfirmedEvent.saga_started_at:type_name -> google.protobuf.Timestamp
	8, // 4: events.ConsignmentConfirmationFailedEvent.saga_started_at:type_name -> google.protobuf.Timestamp
	0, // 5: events.CapacityEvent.action:type_name -> events.CapacityAction
	1, // 6: events.CapacityEvent.reservation_info:type_name -> events.ReservationInfo
	8, // 7: events.CapacityEvent.saga_started_at:type_name -> google.protobuf.Timestamp
	8, // [8:8] is the sub-list for method output_type
	8, // [8:8] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() { file_proto_events_events_proto_init() }
func file_proto_events_events_proto_init() {
	if File_proto_events_events_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_events_events_proto_rawDesc), len(file_proto_events_events_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_events_events_proto_goTypes,
		DependencyIndexes: file_proto_events_events_proto_depIdxs,
		EnumInfos:         file_proto_events_events_proto_enumTypes,
		MessageInfos:      file_proto_events_events_proto_msgTypes,
	}.Build()
	File_proto_events_events_proto = out.File
	file_proto_events_events_proto_goTypes = nil
	file_proto_events_events_proto_depIdxs = nil
}
