// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v5.29.3
// source: proto/consignment/consignment.proto

package consignment

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ConsignmentService_CreateConsignment_FullMethodName  = "/consignment.ConsignmentService/CreateConsignment"
	ConsignmentService_ConfirmConsignment_FullMethodName = "/consignment.ConsignmentService/ConfirmConsignment"
	ConsignmentService_GetConsignments_FullMethodName    = "/consignment.ConsignmentService/GetConsignments"
)

// ConsignmentServiceClient is the client API for ConsignmentService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ConsignmentServiceClient interface {
	CreateConsignment(ctx context.Context, in *Consignment, opts ...grpc.CallOption) (*Response, error)
	ConfirmConsignment(ctx context.Context, in *ConfirmRequest, opts ...grpc.CallOption) (*ConfirmResponse, error)
	GetConsignments(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*Response, error)
}

type consignmentServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewConsignmentServiceClient(cc grpc.ClientConnInterface) ConsignmentServiceClient {
	return &consignmentServiceClient{cc}
}

func (c *consignmentServiceClient) CreateConsignment(ctx context.Context, in *Consignment, opts ...grpc.CallOption) (*Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Response)
	err := c.cc.Invoke(ctx, ConsignmentService_CreateConsignment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *consignmentServiceClient) ConfirmConsignment(ctx context.Context, in *ConfirmRequest, opts ...grpc.CallOption) (*ConfirmResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConfirmResponse)
	err := c.cc.Invoke(ctx, ConsignmentService_ConfirmConsignment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *consignmentServiceClient) GetConsignments(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Response)
	err := c.cc.Invoke(ctx, ConsignmentService_GetConsignments_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ConsignmentServiceServer is the server API for ConsignmentService service.
// All implementations must embed UnimplementedConsignmentServiceServer
// for forward compatibility.
type ConsignmentServiceServer interface {
	CreateConsignment(context.Context, *Consignment) (*Response, error)
	ConfirmConsignment(context.Context, *ConfirmRequest) (*ConfirmResponse, error)
	GetConsignments(context.Context, *GetRequest) (*Response, error)
	mustEmbedUnimplementedConsignmentServiceServer()
}

// UnimplementedConsignmentServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedConsignmentServiceServer struct{}

func (UnimplementedConsignmentServiceServer) CreateConsignment(context.Context, *Consignment) (*Response, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateConsignment not implemented")
}
func (UnimplementedConsignmentServiceServer) ConfirmConsignment(context.Context, *ConfirmRequest) (*ConfirmResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ConfirmConsignment not implemented")
}
func (UnimplementedConsignmentServiceServer) GetConsignments(context.Context, *GetRequest) (*Response, error) {
	return nil, status.Error(codes.Unimplemented, "method GetConsignments not implemented")
}
func (UnimplementedConsignmentServiceServer) mustEmbedUnimplementedConsignmentServiceServer() {}
func (UnimplementedConsignmentServiceServer) testEmbeddedByValue()                            {}

// UnsafeConsignmentServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ConsignmentServiceServer will
// result in compilation errors.
type UnsafeConsignmentServiceServer interface {
	mustEmbedUnimplementedConsignmentServiceServer()
}

func RegisterConsignmentServiceServer(s grpc.ServiceRegistrar, srv ConsignmentServiceServer) {
	// If the following call panics, it indicates UnimplementedConsignmentServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ConsignmentService_ServiceDesc, srv)
}

func _ConsignmentService_CreateConsignment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Consignment)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConsignmentServiceServer).CreateConsignment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConsignmentService_CreateConsignment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConsignmentServiceServer).CreateConsignment(ctx, req.(*Consignment))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConsignmentService_ConfirmConsignment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConfirmRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConsignmentServiceServer).ConfirmConsignment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConsignmentService_ConfirmConsignment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConsignmentServiceServer).ConfirmConsignment(ctx, req.(*ConfirmRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConsignmentService_GetConsignments_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConsignmentServiceServer).GetConsignments(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConsignmentService_GetConsignments_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConsignmentServiceServer).GetConsignments(ctx, req.(*GetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ConsignmentService_ServiceDesc is the grpc.ServiceDesc for ConsignmentService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ConsignmentService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "consignment.ConsignmentService",
	HandlerType: (*ConsignmentServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateConsignment",
			Handler:    _ConsignmentService_CreateConsignment_Handler,
		},
		{
			MethodName: "ConfirmConsignment",
			Handler:    _ConsignmentService_ConfirmConsignment_Handler,
		},
		{
			MethodName: "GetConsignments",
			Handler:    _ConsignmentService_GetConsignments_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/consignment/consignment.proto",
}
