// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: proto/consignment/consignment.proto

package consignment

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ConsignmentStatus int32

const (
	ConsignmentStatus_PENDING   ConsignmentStatus = 0
	ConsignmentStatus_CONFIRMED ConsignmentStatus = 1
	ConsignmentStatus_CANCELLED ConsignmentStatus = 2
)

// Enum value maps for ConsignmentStatus.
var (
	ConsignmentStatus_name = map[int32]string{
		0: "PENDING",
		1: "CONFIRMED",
		2: "CANCELLED",
	}
	ConsignmentStatus_value = map[string]int32{
		"PENDING":   0,
		"CONFIRMED": 1,
		"CANCELLED": 2,
	}
)

func (x ConsignmentStatus) Enum() *ConsignmentStatus {
	p := new(ConsignmentStatus)
	*p = x
	return p
}

func (x ConsignmentStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ConsignmentStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_consignment_consignment_proto_enumTypes[0].Descriptor()
}

func (ConsignmentStatus) Type() protoreflect.EnumType {
	return &file_proto_consignment_consignment_proto_enumTypes[0]
}

func (x ConsignmentStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ConsignmentStatus.Descriptor instead.
func (ConsignmentStatus) EnumDescriptor() ([]byte, []int) {
	return file_proto_consignment_consignment_proto_rawDescGZIP(), []int{0}
}

type Consignment struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Weight        int32                  `protobuf:"varint,3,opt,name=weight,proto3" json:"weight,omitempty"`
	Containers    []*Container           `protobuf:"bytes,4,rep,name=containers,proto3" json:"containers,omitempty"`
	VesselId      string                 `protobuf:"bytes,5,opt,name=vessel_id,json=vesselId,proto3" json:"vessel_id,omitempty"`
	Status        ConsignmentStatus      `protobuf:"varint,6,opt,name=status,proto3,enum=consignment.ConsignmentStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Consignment) Reset() {
	*x = Consignment{}
	mi := &file_proto_consignment_consignment_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Consignment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Consignment) ProtoMessage() {}

func (x *Consignment) ProtoReflect() protoreflect.Message {
	mi := &file_proto_consignment_consignment_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Consignment.ProtoReflect.Descriptor instead.
func (*Consignment) Descriptor() ([]byte, []int) {
	return file_proto_consignment_consignment_proto_rawDescGZIP(), []int{0}
}

func (x *Consignment) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Consignment) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Consignment) GetWeight() int32 {
	if x != nil {
		return x.Weight
	}
	return 0
}

func (x *Consignment) GetContainers() []*Container {
	if x != nil {
		return x.Containers
	}
	return nil
}

func (x *Consignment) GetVesselId() string {
	if x != nil {
		return x.VesselId
	}
	return ""
}

func (x *Consignment) GetStatus() ConsignmentStatus {
	if x != nil {
		return x.Status
	}
	return ConsignmentStatus_PENDING
}

type Container struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CustomerId    string                 `protobuf:"bytes,2,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	Origin        string                 `protobuf:"bytes,3,opt,name=origin,proto3" json:"origin,omitempty"`
	UserId        string                 `protobuf:"bytes,4,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Container) Reset() {
	*x = Container{}
	mi := &file_proto_consignment_consignment_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Container) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Container) ProtoMessage() {}

func (x *Container) ProtoReflect() protoreflect.Message {
	mi := &file_proto_consignment_consignment_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Container.ProtoReflect.Descriptor instead.
func (*Container) Descriptor() ([]byte, []int) {
	return file_proto_consignment_consignment_proto_rawDescGZIP(), []int{1}
}

func (x *Container) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Container) GetCustomerId() string {
	if x != nil {
		return x.CustomerId
	}
	return ""
}

func (x *Container) GetOrigin() string {
	if x != nil {
		return x.Origin
	}
	return ""
}

func (x *Container) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Created       bool                   `protobuf:"varint,1,opt,name=created,proto3" json:"created,omitempty"`
	Consignment   *Consignment           `protobuf:"bytes,2,opt,name=consignment,proto3" json:"consignment,omitempty"`
	Consignments  []*Consignment         `protobuf:"bytes,3,rep,name=consignments,proto3" json:"consignments,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Response) Reset() {
	*x = Response{}
	mi := &file_proto_consignment_consignment_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_proto_consignment_consignment_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_proto_consignment_consignment_proto_rawDescGZIP(), []int{2}
}

func (x *Response) GetCreated() bool {
	if x != nil {
		return x.Created
	}
	return false
}

func (x *Response) GetConsignment() *Consignment {
	if x != nil {
		return x.Consignment
	}
	return nil
}

func (x *Response) GetConsignments() []*Consignment {
	if x != nil {
		return x.Consignments
	}
	return nil
}

type GetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRequest) Reset() {
	*x = GetRequest{}
	mi := &file_proto_consignment_consignment_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRequest) ProtoMessage() {}

func (x *GetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_consignment_consignment_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRequest.ProtoReflect.Descriptor instead.
func (*GetRequest) Descriptor() ([]byte, []int) {
	return file_proto_consignment_consignment_proto_rawDescGZIP(), []int{3}
}

type ConfirmRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfirmRequest) Reset() {
	*x = ConfirmRequest{}
	mi := &file_proto_consignment_consignment_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfirmRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfirmRequest) ProtoMessage() {}

func (x *ConfirmRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_consignment_consignment_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfirmRequest.ProtoReflect.Descriptor instead.
func (*ConfirmRequest) Descriptor() ([]byte, []int) {
	return file_proto_consignment_consignment_proto_rawDescGZIP(), []int{4}
}

func (x *ConfirmRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ConfirmResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Confirmed     bool                   `protobuf:"varint,1,opt,name=confirmed,proto3" json:"confirmed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfirmResponse) Reset() {
	*x = ConfirmResponse{}
	mi := &file_proto_consignment_consignment_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfirmResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfirmResponse) ProtoMessage() {}

func (x *ConfirmResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_consignment_consignment_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfirmResponse.ProtoReflect.Descriptor instead.
func (*ConfirmResponse) Descriptor() ([]byte, []int) {
	return file_proto_consignment_consignment_proto_rawDescGZIP(), []int{5}
}

func (x *ConfirmResponse) GetConfirmed() bool {
	if x != nil {
		return x.Confirmed
	}
	return false
}

var File_proto_consignment_consignment_proto protoreflect.FileDescriptor

const file_proto_consignment_consignment_proto_rawDesc = "" +
	"\n" +
	"#proto/consignment/consignment.proto\x12\vconsignment\"\xe4\x01\n" +
	"\vConsignment\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x16\n" +
	"\x06weight\x18\x03 \x01(\x05R\x06weight\x126\n" +
	"\n" +
	"containers\x18\x04 \x03(\v2\x16.consignment.ContainerR\n" +
	"containers\x12\x1b\n" +
	"\tvessel_id\x18\x05 \x01(\tR\bvesselId\x126\n" +
	"\x06status\x18\x06 \x01(\x0e2\x1e.consignment.ConsignmentStatusR\x06status\"m\n" +
	"\tContainer\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1f\n" +
	"\vcustomer_id\x18\x02 \x01(\tR\n" +
	"customerId\x12\x16\n" +
	"\x06origin\x18\x03 \x01(\tR\x06origin\x12\x17\n" +
	"\auser_id\x18\x04 \x01(\tR\x06userId\"\x9e\x01\n" +
	"\bResponse\x12\x18\n" +
	"\acreated\x18\x01 \x01(\bR\acreated\x12:\n" +
	"\vconsignment\x18\x02 \x01(\v2\x18.consignment.ConsignmentR\vconsignment\x12<\n" +
	"\fconsignments\x18\x03 \x03(\v2\x18.consignment.ConsignmentR\fconsignments\"\f\n" +
	"\n" +
	"GetRequest\" \n" +
	"\x0eConfirmRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"/\n" +
	"\x0fConfirmResponse\x12\x1c\n" +
	"\tconfirmed\x18\x01 \x01(\bR\tconfirmed*>\n" +
	"\x11ConsignmentStatus\x12\v\n" +
	"\aPENDING\x10\x00\x12\r\n" +
	"\tCONFIRMED\x10\x01\x12\r\n" +
	"\tCANCELLED\x10\x022\xee\x01\n" +
	"\x12ConsignmentService\x12D\n" +
	"\x11CreateConsignment\x12\x18.consignment.Consignment\x1a\x15.consignment.Response\x12O\n" +
	"\x12ConfirmConsignment\x12\x1b.consignment.ConfirmRequest\x1a\x1c.consignment.ConfirmResponse\x12A\n" +
	"\x0fGetConsignments\x12\x17.consignment.GetRequest\x1a\x15.consignment.ResponseB5Z3github.com/murraystewart96/shippy/proto/consignmentb\x06proto3"

var (
	file_proto_consignment_consignment_proto_rawDescOnce sync.Once
	file_proto_consignment_consignment_proto_rawDescData []byte
)

func file_proto_consignment_consignment_proto_rawDescGZIP() []byte {
	file_proto_consignment_consignment_proto_rawDescOnce.Do(func() {
		file_proto_consignment_consignment_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_consignment_consignment_proto_rawDesc), len(file_proto_consignment_consignment_proto_rawDesc)))
	})
	return file_proto_consignment_consignment_proto_rawDescData
}

var file_proto_consignment_consignment_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_consignment_consignment_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_consignment_consignment_proto_goTypes = []any{
	(ConsignmentStatus)(0),  // 0: consignment.ConsignmentStatus
	(*Consignment)(nil),     // 1: consignment.Consignment
	(*Container)(nil),       // 2: consignment.Container
	(*Response)(nil),        // 3: consignment.Response
	(*GetRequest)(nil),      // 4: consignment.GetRequest
	(*ConfirmRequest)(nil),  // 5: consignment.ConfirmRequest
	(*ConfirmResponse)(nil), // 6: consignment.ConfirmResponse
}
var file_proto_consignment_consignment_proto_depIdxs = []int32{
	2, // 0: consignment.Consignment.containers:type_name -> consignment.Container
	0, // 1: consignment.Consignment.status:type_name -> consignment.ConsignmentStatus
	1, // 2: consignment.Response.consignment:type_name -> consignment.Consignment
	1, // 3: consignment.Response.consignments:type_name -> consignment.Consignment
	1, // 4: consignment.ConsignmentService.CreateConsignment:input_type -> consignment.Consignment
	5, // 5: consignment.ConsignmentService.ConfirmConsignment:input_type -> consignment.ConfirmRequest
	4, // 6: consignment.ConsignmentService.GetConsignments:input_type -> consignment.GetRequest
	3, // 7: consignment.ConsignmentService.CreateConsignment:output_type -> consignment.Response
	6, // 8: consignment.ConsignmentService.ConfirmConsignment:output_type -> consignment.ConfirmResponse
	3, // 9: consignment.ConsignmentService.GetConsignments:output_type -> consignment.Response
	7, // [7:10] is the sub-list for method output_type
	4, // [4:7] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_proto_consignment_consignment_proto_init() }
func file_proto_consignment_consignment_proto_init() {
	if File_proto_consignment_consignment_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_consignment_consignment_proto_rawDesc), len(file_proto_consignment_consignment_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_consignment_consignment_proto_goTypes,
		DependencyIndexes: file_proto_consignment_consignment_proto_depIdxs,
		EnumInfos:         file_proto_consignment_consignment_proto_enumTypes,
		MessageInfos:      file_proto_consignment_consignment_proto_msgTypes,
	}.Build()
	File_proto_consignment_consignment_proto = out.File
	file_proto_consignment_consignment_proto_goTypes = nil
	file_proto_consignment_consignment_proto_depIdxs = nil
}
